# Generated by scripts/generate_command_artifacts.py. DO NOT EDIT.
set(RHBM_GEM_GENERATED_CORE_COMMAND_TEST_SOURCES
    core/command/PotentialAnalysisCommand_test.cpp
    core/command/PotentialDisplayCommand_test.cpp
    core/command/ResultDumpCommand_test.cpp
    core/command/MapSimulationCommand_test.cpp
    core/command/MapVisualizationCommand_test.cpp
    core/command/PositionEstimationCommand_test.cpp
    core/command/HRLModelTestCommand_test.cpp
)
