#!/usr/bin/env python3
"""Generate command artifacts from CommandList.def."""

from __future__ import annotations

from pathlib import Path
import argparse
import sys

from command_manifest import CommandEntry, collect_drift_paths, parse_commands


BEGIN_MANIFEST = "<!-- BEGIN GENERATED: command-manifest -->"
END_MANIFEST = "<!-- END GENERATED: command-manifest -->"
BEGIN_MATRIX = "<!-- BEGIN GENERATED: command-surface-matrix -->"
END_MATRIX = "<!-- END GENERATED: command-surface-matrix -->"
BEGIN_PYTHON = "<!-- BEGIN GENERATED: command-python-surface -->"
END_PYTHON = "<!-- END GENERATED: command-python-surface -->"

def build_catalog_includes(entries: list[CommandEntry]) -> str:
    lines = [
        "// Generated by scripts/developer/generate_command_artifacts.py. DO NOT EDIT.",
        "",
    ]
    lines.extend(
        f"#include <rhbm_gem/core/command/{entry.command_type}.hpp>" for entry in entries
    )
    lines.append("")
    return "\n".join(lines)


def build_catalog_entries(entries: list[CommandEntry]) -> str:
    lines = [
        "// Generated by scripts/developer/generate_command_artifacts.py. DO NOT EDIT.",
        "",
    ]
    lines.extend(
        (
            f"MakeCommandDescriptor<{entry.command_type}>("
            f"\"{entry.cli_name}\", \"{entry.description}\"),"
        )
        for entry in entries
    )
    lines.append("")
    return "\n".join(lines)


def build_command_id_entries(entries: list[CommandEntry]) -> str:
    lines = ["// Generated by scripts/developer/generate_command_artifacts.py. DO NOT EDIT.", ""]
    for index, entry in enumerate(entries):
        if index == 0:
            lines.append(f"{entry.command_id} = 0,")
            continue
        lines.append(f"{entry.command_id},")
    lines.append("")
    return "\n".join(lines)


def build_binding_name_traits(entries: list[CommandEntry]) -> str:
    lines = ["// Generated by scripts/developer/generate_command_artifacts.py. DO NOT EDIT.", ""]
    for entry in entries:
        lines.extend(
            [
                "template <>",
                f"struct CommandBindingName<{entry.command_type}>",
                "{",
                f'    static constexpr std::string_view value{{ "{entry.python_binding_name}" }};',
                "};",
                "",
            ]
        )
    return "\n".join(lines)


def build_command_sources(entries: list[CommandEntry]) -> str:
    lines = [
        "# Generated by scripts/developer/generate_command_artifacts.py. DO NOT EDIT.",
        "set(RHBM_GEM_COMMAND_SOURCES",
    ]
    lines.extend(f"    core/command/{entry.command_type}.cpp" for entry in entries)
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def build_command_binding_sources(entries: list[CommandEntry]) -> str:
    lines = [
        "# Generated by scripts/developer/generate_command_artifacts.py. DO NOT EDIT.",
        "set(RHBM_GEM_COMMAND_BINDING_SOURCES",
    ]
    for entry in entries:
        stem = entry.command_type.removesuffix("Command")
        lines.append(f"    {stem}Bindings.cpp")
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def build_command_tests(entries: list[CommandEntry]) -> str:
    lines = [
        "# Generated by scripts/developer/generate_command_artifacts.py. DO NOT EDIT.",
        "set(RHBM_GEM_GENERATED_CORE_COMMAND_TEST_SOURCES",
    ]
    lines.extend(
        f"    core/command/{entry.command_type}_test.cpp" for entry in entries
    )
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def build_manifest_block(entries: list[CommandEntry]) -> str:
    return "".join(f"{index}. `{entry.cli_name}`\n" for index, entry in enumerate(entries, 1))


def build_surface_matrix_block(entries: list[CommandEntry]) -> str:
    lines = [
        "| Command | Uses database at runtime | Uses output folder |",
        "| --- | --- | --- |",
    ]
    for entry in entries:
        uses_database = "yes" if entry.profile == "DatabaseWorkflow" else "no"
        uses_output = "yes"
        lines.append(f"| `{entry.cli_name}` | {uses_database} | {uses_output} |")
    return "\n".join(lines) + "\n"


def build_python_surface_block(entries: list[CommandEntry]) -> str:
    lines = ["### Python command classes"]
    lines.extend(f"- `{entry.python_binding_name}`" for entry in entries)

    lines.extend(
        [
            "",
            "### Shared diagnostics types",
            "- `LogLevel`",
            "- `ValidationPhase`",
            "- `ValidationIssue`",
            "",
            "### Shared diagnostics methods on Python commands",
            "- `PrepareForExecution()`",
            "- `HasValidationErrors()`",
            "- `GetValidationIssues()`",
        ]
    )
    return "\n".join(lines) + "\n"


def replace_generated_block(
    text: str,
    begin_marker: str,
    end_marker: str,
    replacement_block: str,
) -> str:
    begin = text.find(begin_marker)
    if begin == -1:
        raise RuntimeError(f"Missing begin marker: {begin_marker}")

    block_begin = text.find("\n", begin)
    if block_begin == -1:
        raise RuntimeError(f"Malformed marker line: {begin_marker}")
    block_begin += 1

    end = text.find(end_marker, block_begin)
    if end == -1:
        raise RuntimeError(f"Missing end marker: {end_marker}")

    return text[:block_begin] + replacement_block + text[end:]


def build_updated_docs(root: Path, entries: list[CommandEntry]) -> str:
    doc_path = root / "docs" / "developer" / "architecture" / "command-architecture.md"
    doc = doc_path.read_text(encoding="utf-8")
    doc = replace_generated_block(doc, BEGIN_MANIFEST, END_MANIFEST, build_manifest_block(entries))
    doc = replace_generated_block(doc, BEGIN_MATRIX, END_MATRIX, build_surface_matrix_block(entries))
    doc = replace_generated_block(doc, BEGIN_PYTHON, END_PYTHON, build_python_surface_block(entries))
    return doc


def compute_expected_outputs(
    root: Path,
    entries: list[CommandEntry]) -> list[tuple[Path, str]]:
    return [
        (
            root / "include" / "rhbm_gem" / "core" / "command" / "internal"
            / "CommandIdEntries.generated.inc",
            build_command_id_entries(entries),
        ),
        (
            root / "src" / "core" / "internal" / "CommandCatalogIncludes.generated.inc",
            build_catalog_includes(entries),
        ),
        (
            root / "src" / "core" / "internal" / "CommandCatalogEntries.generated.inc",
            build_catalog_entries(entries),
        ),
        (
            root / "bindings" / "internal" / "CommandBindingNames.generated.inc",
            build_binding_name_traits(entries),
        ),
        (
            root / "src" / "CommandSources.generated.cmake",
            build_command_sources(entries),
        ),
        (
            root / "bindings" / "CommandBindingUnits.generated.cmake",
            build_command_binding_sources(entries),
        ),
        (
            root / "tests" / "cmake" / "CoreCommandTests.generated.cmake",
            build_command_tests(entries),
        ),
        (
            root / "docs" / "developer" / "architecture" / "command-architecture.md",
            build_updated_docs(root, entries),
        ),
    ]


def write_if_changed(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    changed = current != content
    if changed and not check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated artifacts are up to date without writing changes.",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[2]
    command_path = root / "src" / "core" / "internal" / "CommandList.def"
    entries = parse_commands(command_path)
    if not entries:
        print("No commands parsed from CommandList.def")
        return 1

    outputs = compute_expected_outputs(root, entries)

    changed_paths: list[Path] = []
    if args.check:
        changed_paths = collect_drift_paths(outputs)
    else:
        for path, content in outputs:
            if write_if_changed(path, content, check=False):
                changed_paths.append(path)

    if args.check:
        if changed_paths:
            print("Command artifacts are out of date:")
            for path in changed_paths:
                print(f" - {path.relative_to(root)}")
            print("Run: python3 scripts/developer/generate_command_artifacts.py")
            return 1
        print(f"Command artifacts are up to date ({len(entries)} commands).")
        return 0

    for path in changed_paths:
        print(f"updated {path.relative_to(root)}")
    if not changed_paths:
        print(f"Command artifacts already up to date ({len(entries)} commands).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
