#!/usr/bin/env python3
"""Generate built-in command artifacts from BuiltInCommandList.def."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import argparse
import re
import sys


@dataclass(frozen=True)
class CommandEntry:
    command_type: str
    cli_name: str
    description: str


BEGIN_MANIFEST = "<!-- BEGIN GENERATED: built-in-command-manifest -->"
END_MANIFEST = "<!-- END GENERATED: built-in-command-manifest -->"
BEGIN_MATRIX = "<!-- BEGIN GENERATED: command-surface-matrix -->"
END_MATRIX = "<!-- END GENERATED: command-surface-matrix -->"
BEGIN_PYTHON = "<!-- BEGIN GENERATED: built-in-python-command-surface -->"
END_PYTHON = "<!-- END GENERATED: built-in-python-command-surface -->"


def parse_builtins(path: Path) -> list[CommandEntry]:
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(
        r"RHBM_GEM_BUILTIN_COMMAND\(\s*"
        r"(?P<command>[A-Za-z_][A-Za-z0-9_]*)\s*,\s*"
        r"\"(?P<cli>[^\"]+)\"\s*,\s*"
        r"\"(?P<desc>[^\"]*)\"\s*"
        r"\)",
        re.MULTILINE,
    )
    return [
        CommandEntry(
            command_type=match.group("command"),
            cli_name=match.group("cli"),
            description=match.group("desc"),
        )
        for match in pattern.finditer(text)
    ]


def command_uses_database(root: Path, command_type: str) -> bool:
    header = root / "include" / "rhbm_gem" / "core" / "command" / f"{command_type}.hpp"
    if not header.exists():
        return False

    text = header.read_text(encoding="utf-8")
    if "CommonOptionProfile::DatabaseWorkflow" in text:
        return True
    if "CommonOptionProfile::FileWorkflow" in text:
        return False

    # Fallback for explicit CommonOption mask declarations.
    return "CommonOption::Database" in text


def command_uses_output_folder(root: Path, command_type: str) -> bool:
    header = root / "include" / "rhbm_gem" / "core" / "command" / f"{command_type}.hpp"
    if not header.exists():
        return True

    text = header.read_text(encoding="utf-8")
    if "CommonOptionProfile::DatabaseWorkflow" in text:
        return True
    if "CommonOptionProfile::FileWorkflow" in text:
        return True
    if "CommandWithProfileOptions<" in text:
        return True

    # Fallback for explicit CommonOption mask declarations.
    return "CommonOption::OutputFolder" in text


def build_catalog_includes(entries: list[CommandEntry]) -> str:
    lines = [
        "// Generated by scripts/generate_builtin_command_artifacts.py. DO NOT EDIT.",
        "",
    ]
    lines.extend(
        f"#include <rhbm_gem/core/command/{entry.command_type}.hpp>" for entry in entries
    )
    lines.append("")
    return "\n".join(lines)


def build_catalog_entries(entries: list[CommandEntry]) -> str:
    lines = [
        "// Generated by scripts/generate_builtin_command_artifacts.py. DO NOT EDIT.",
        "",
    ]
    lines.extend(
        (
            f"MakeBuiltInDescriptor<{entry.command_type}>("
            f"\"{entry.command_type}\", \"{entry.cli_name}\", \"{entry.description}\"),"
        )
        for entry in entries
    )
    lines.append("")
    return "\n".join(lines)


def build_builtin_command_sources(entries: list[CommandEntry]) -> str:
    lines = [
        "# Generated by scripts/generate_builtin_command_artifacts.py. DO NOT EDIT.",
        "set(RHBM_GEM_BUILTIN_COMMAND_SOURCES",
    ]
    lines.extend(f"    core/command/{entry.command_type}.cpp" for entry in entries)
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def build_builtin_binding_sources(entries: list[CommandEntry]) -> str:
    lines = [
        "# Generated by scripts/generate_builtin_command_artifacts.py. DO NOT EDIT.",
        "set(RHBM_GEM_BUILTIN_BINDING_SOURCES",
    ]
    for entry in entries:
        stem = entry.command_type.removesuffix("Command")
        lines.append(f"    {stem}Bindings.cpp")
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def build_builtin_command_tests(entries: list[CommandEntry]) -> str:
    lines = [
        "# Generated by scripts/generate_builtin_command_artifacts.py. DO NOT EDIT.",
        "set(RHBM_GEM_BUILTIN_CORE_COMMAND_TEST_SOURCES",
    ]
    lines.extend(
        f"    core/command/{entry.command_type}_test.cpp" for entry in entries
    )
    lines.append(")")
    lines.append("")
    return "\n".join(lines)


def build_manifest_block(entries: list[CommandEntry]) -> str:
    return "".join(f"{index}. `{entry.cli_name}`\n" for index, entry in enumerate(entries, 1))


def build_surface_matrix_block(root: Path, entries: list[CommandEntry]) -> str:
    lines = [
        "| Command | Uses database at runtime | Uses output folder |",
        "| --- | --- | --- |",
    ]
    for entry in entries:
        uses_database = "yes" if command_uses_database(root, entry.command_type) else "no"
        uses_output = "yes" if command_uses_output_folder(root, entry.command_type) else "no"
        lines.append(f"| `{entry.cli_name}` | {uses_database} | {uses_output} |")
    return "\n".join(lines) + "\n"


def build_python_surface_block(entries: list[CommandEntry]) -> str:
    lines = ["### Built-in Python command classes"]
    lines.extend(f"- `{entry.command_type}`" for entry in entries)

    lines.extend(
        [
            "",
            "### Shared diagnostics types",
            "- `LogLevel`",
            "- `ValidationPhase`",
            "- `ValidationIssue`",
            "",
            "### Shared diagnostics methods on built-in Python commands",
            "- `PrepareForExecution()`",
            "- `HasValidationErrors()`",
            "- `GetValidationIssues()`",
        ]
    )
    return "\n".join(lines) + "\n"


def replace_generated_block(
    text: str,
    begin_marker: str,
    end_marker: str,
    replacement_block: str,
) -> str:
    begin = text.find(begin_marker)
    if begin == -1:
        raise RuntimeError(f"Missing begin marker: {begin_marker}")

    block_begin = text.find("\n", begin)
    if block_begin == -1:
        raise RuntimeError(f"Malformed marker line: {begin_marker}")
    block_begin += 1

    end = text.find(end_marker, block_begin)
    if end == -1:
        raise RuntimeError(f"Missing end marker: {end_marker}")

    return text[:block_begin] + replacement_block + text[end:]


def build_updated_docs(root: Path, entries: list[CommandEntry]) -> str:
    doc_path = root / "docs" / "developer" / "architecture" / "command-architecture.md"
    doc = doc_path.read_text(encoding="utf-8")
    doc = replace_generated_block(doc, BEGIN_MANIFEST, END_MANIFEST, build_manifest_block(entries))
    doc = replace_generated_block(doc, BEGIN_MATRIX, END_MATRIX, build_surface_matrix_block(root, entries))
    doc = replace_generated_block(doc, BEGIN_PYTHON, END_PYTHON, build_python_surface_block(entries))
    return doc


def write_if_changed(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else ""
    changed = current != content
    if changed and not check:
        path.write_text(content, encoding="utf-8")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated artifacts are up to date without writing changes.",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    builtins_path = root / "src" / "core" / "internal" / "BuiltInCommandList.def"
    entries = parse_builtins(builtins_path)
    if not entries:
        print("No built-in commands parsed from BuiltInCommandList.def")
        return 1

    outputs: list[tuple[Path, str]] = [
        (
            root / "src" / "core" / "internal" / "BuiltInCommandCatalogIncludes.generated.inc",
            build_catalog_includes(entries),
        ),
        (
            root / "src" / "core" / "internal" / "BuiltInCommandCatalogEntries.generated.inc",
            build_catalog_entries(entries),
        ),
        (
            root / "src" / "BuiltInCommandSources.generated.cmake",
            build_builtin_command_sources(entries),
        ),
        (
            root / "bindings" / "BuiltInBindingUnits.generated.cmake",
            build_builtin_binding_sources(entries),
        ),
        (
            root / "tests" / "cmake" / "BuiltInCoreCommandTests.generated.cmake",
            build_builtin_command_tests(entries),
        ),
        (
            root / "docs" / "developer" / "architecture" / "command-architecture.md",
            build_updated_docs(root, entries),
        ),
    ]

    changed_paths: list[Path] = []
    for path, content in outputs:
        if write_if_changed(path, content, check=args.check):
            changed_paths.append(path)

    if args.check:
        if changed_paths:
            print("Built-in command artifacts are out of date:")
            for path in changed_paths:
                print(f" - {path.relative_to(root)}")
            print("Run: python3 scripts/generate_builtin_command_artifacts.py")
            return 1
        print(f"Built-in command artifacts are up to date ({len(entries)} commands).")
        return 0

    for path in changed_paths:
        print(f"updated {path.relative_to(root)}")
    if not changed_paths:
        print(f"Built-in command artifacts already up to date ({len(entries)} commands).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
