# Generated by scripts/generate_builtin_command_artifacts.py. DO NOT EDIT.
set(RHBM_GEM_BUILTIN_BINDING_SOURCES
    PotentialAnalysisBindings.cpp
    PotentialDisplayBindings.cpp
    ResultDumpBindings.cpp
    MapSimulationBindings.cpp
    MapVisualizationBindings.cpp
    PositionEstimationBindings.cpp
    HRLModelTestBindings.cpp
)
