# Generated by scripts/generate_builtin_command_artifacts.py. DO NOT EDIT.
set(RHBM_GEM_BUILTIN_COMMAND_SOURCES
    core/command/PotentialAnalysisCommand.cpp
    core/command/PotentialDisplayCommand.cpp
    core/command/ResultDumpCommand.cpp
    core/command/MapSimulationCommand.cpp
    core/command/MapVisualizationCommand.cpp
    core/command/PositionEstimationCommand.cpp
    core/command/HRLModelTestCommand.cpp
)
