include("${CMAKE_CURRENT_LIST_DIR}/GuardCommon.cmake")
rhbm_guard_require_project_source_dir()
rhbm_guard_find_git(GIT_EXECUTABLE)
rhbm_guard_get_tracked_files("${GIT_EXECUTABLE}" TRACKED_FILE_LIST)

set(HYGIENE_VIOLATIONS)
foreach(TRACKED_FILE IN LISTS TRACKED_FILE_LIST)
    if(TRACKED_FILE MATCHES "^CMakeFiles/")
        list(APPEND HYGIENE_VIOLATIONS "${TRACKED_FILE} (generated CMake metadata must not be tracked)")
    elseif(TRACKED_FILE MATCHES "^build/")
        list(APPEND HYGIENE_VIOLATIONS "${TRACKED_FILE} (build artifacts must not be tracked)")
    elseif(TRACKED_FILE MATCHES "(^|/)\\.DS_Store$")
        list(APPEND HYGIENE_VIOLATIONS "${TRACKED_FILE} (OS metadata must not be tracked)")
    elseif(TRACKED_FILE MATCHES "^[^/]+\\.sqlite$")
        list(APPEND HYGIENE_VIOLATIONS "${TRACKED_FILE} (root-level sqlite files must be moved to data/local/)")
    elseif(TRACKED_FILE MATCHES "^[^/]+\\.db$")
        list(APPEND HYGIENE_VIOLATIONS "${TRACKED_FILE} (root-level db files must be moved to data/local/)")
    elseif(TRACKED_FILE MATCHES "^[^/]+\\.sh$")
        list(APPEND HYGIENE_VIOLATIONS "${TRACKED_FILE} (root-level scripts must move under scripts/)")
    elseif(TRACKED_FILE MATCHES "^data/local/")
        list(APPEND HYGIENE_VIOLATIONS "${TRACKED_FILE} (data/local/ is reserved for ignored local datasets)")
    endif()
endforeach()

if(HYGIENE_VIOLATIONS)
    list(JOIN HYGIENE_VIOLATIONS "\n  - " HYGIENE_VIOLATIONS_TEXT)
    message(FATAL_ERROR
        "Repository hygiene guard failed.\n"
        "  - ${HYGIENE_VIOLATIONS_TEXT}\n"
        "Move generated/local artifacts to ignored locations before committing.")
endif()
